# Generated by Django 5.0.6 on 2024-05-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departue_city', models.CharField(max_length=100)),
                ('arrivel_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrivel_date', models.DateField()),
                ('airline', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
