# Generated by Django 5.0.6 on 2024-05-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightfare',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='flight_id',
        ),
        migrations.RemoveField(
            model_name='flightfare',
            name='origin_airport',
        ),
    ]
