# Generated by Django 5.0.6 on 2024-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
