# Generated by Django 5.0.6 on 2024-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_payment_reservation'),
        ('users', '0005_remove_payment_order_delete_order_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
