# Generated by Django 5.0.6 on 2024-05-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_reservation_flight'),
        ('users', '0006_delete_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
