# Generated by Django 5.0.6 on 2024-05-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departue_city', models.CharField(max_length=100)),
                ('arrivel_city', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('arrivel_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airline.airline')),
            ],
        ),
    ]
