# Generated by Django 5.0.6 on 2024-05-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='departue_city',
            new_name='departure_city',
        ),
    ]
