# Generated by Django 5.0.6 on 2024-05-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_rename_departue_city_flight_departure_city'),
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flights.flight'),
        ),
    ]
